check:
  image: alpine:latest
  stage: .pre
  before_script:
    - apk update && apk add --no-cache git python3 py3-pip clang
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install pre-commit
  script:
    - pre-commit run --all-files

.build: &build
  image: debian:testing-slim
  stage: build
  before_script:
    - apt update && apt install -y --no-install-recommends ${COMPILER_PACKAGE} git ca-certificates cmake ninja-build libtag1-dev qtbase5-dev qtmultimedia5-dev
  script:
    - cmake . --warn-uninitialized -GNinja -DCMAKE_CXX_COMPILER=${COMPILER} -DSANITIZE_ADDRESS=On
    - ninja -v
    - ASAN_OPTIONS=verbose=1 ctest -V

.arch-build: &arch-build
  image: archlinux/base
  stage: build
  before_script:
    - pacman -Suy --noconfirm git pkg-config cmake ninja gcc python3 taglib qt5-base qt5-multimedia
  script:
    - cmake . --warn-uninitialized -GNinja -DSANITIZE_ADDRESS=On
    - ninja -v
    - ASAN_OPTIONS=verbose=1 ctest -V

build:gcc:
  <<: *build
  variables:
    COMPILER_PACKAGE: "g++"
    COMPILER: "g++"

build:clang:
  <<: *build
  variables:
    COMPILER_PACKAGE: "clang"
    COMPILER: "clang++"

build:arch:
  <<: *arch-build
