image: debian:testing-slim

check:
  stage: .pre
  before_script:
    - apt update && apt install -y --no-install-recommends git python3 python3-pip python3-setuptools python3-wheel clang-format-8
    - ln -s /usr/bin/clang-format-8 /usr/bin/clang-format
    - pip3 install pre-commit
  script:
    - pre-commit run --all-files

build:
  stage: build
  before_script:
    - apt update && apt install -y --no-install-recommends g++ cmake ninja-build libtag1-dev qtbase5-dev qtmultimedia5-dev
  script:
    - cmake . -GNinja
    - ninja
