check:
  image: python:3.10-slim-bullseye
  stage: .pre
  before_script:
    - apt update && apt install -y --no-install-recommends git
    - python3 -m venv venv
    - source venv/bin/activate
    - python -m pip install --disable-pip-version-check --no-cache-dir pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

.build: &build
  image: debian:testing-slim
  stage: build
  before_script:
    - apt update && apt install -y --no-install-recommends ${COMPILER_PACKAGE} git ca-certificates cmake ninja-build libtag1-dev qt6-base-dev qt6-multimedia-dev
  script:
    - cmake . --warn-uninitialized -GNinja -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DSANITIZE_ADDRESS=On
    - ninja -v
    - ASAN_OPTIONS=verbose=1 ctest -V

build:gcc:
  <<: *build
  variables:
    COMPILER_PACKAGE: "g++"
    C_COMPILER: "gcc"
    CXX_COMPILER: "g++"

build:clang:
  <<: *build
  variables:
    COMPILER_PACKAGE: "clang"
    C_COMPILER: "clang"
    CXX_COMPILER: "clang++"
