image: debian:testing-slim

check:
  stage: .pre
  before_script:
    - apt update && apt install -y --no-install-recommends git python3 python3-pip python3-setuptools python3-wheel clang-format-8
    - ln -s /usr/bin/clang-format-8 /usr/bin/clang-format
    - pip3 install pre-commit
  script:
    - pre-commit run --all-files

.build: &build
  stage: build
  before_script:
    - apt update && apt install -y --no-install-recommends ${COMPILER_PACKAGE} git ca-certificates cmake ninja-build libtag1-dev qtbase5-dev qtmultimedia5-dev
  script:
    - cmake . --warn-uninitialized -GNinja -DCMAKE_CXX_COMPILER=${COMPILER}
    - ninja -v
    - ctest

build:gcc:
  <<: *build
  variables:
    COMPILER_PACKAGE: "g++"
    COMPILER: "g++"

build:clang:
  <<: *build
  variables:
    COMPILER_PACKAGE: "clang"
    COMPILER: "clang++"
