image: debian:testing-slim

build:
  stage: build
  before_script: 
    - apt update && apt install -y --no-install-recommends g++ cmake ninja-build libtag1-dev qt5base-dev qtmultimedia5-dev
  script: 
    - cmake . -GNinja
    - ninja
