repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [ --fix, lf ]
-   repo: https://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    -   id: clang-format
